INSERT INTO store VALUES ('Vehicle Store', 832000, 40);
INSERT INTO store VALUES ('Computer Store', 62370, 60);
INSERT INTO store VALUES ('Fashion Store', 82530, 50);
INSERT INTO store VALUES ('Bicycle Store', 55420, 50);
INSERT INTO store VALUES ('Shoe Store', 27530, 60);
INSERT INTO store VALUES ('Media Store', 11320, 70);
INSERT INTO store VALUES ('Hardware Store', 21390, 50);
INSERT INTO store VALUES ('Book Store', 19330, 60);
INSERT INTO store VALUES ('Boat Store', 658320, 30);
INSERT INTO events VALUES (1, 'War!', 'War has broken out between two nations! Population, productivity, and wealth will be severely impacted in affected cities for the duration of the war.');
INSERT INTO events VALUES (2, 'Trade Alliance Signed!', 'A trade agreement has been reached between two nations. Productivity and wealth will be increased during transactions between cities within these nations.');       
INSERT INTO events VALUES (3, 'Global Recession!', 'The global economy is in a recession. Productivity and wealth will be negatively impacted somewhat.');
INSERT INTO events VALUES (4, 'Economic Depression!', 'The global economy is in a depression period. Productivity and wealth is impacted, and populations will move more frequently.');
INSERT INTO events VALUES (5, 'Cyber Attack!', 'One of your stores has been victim to a cyberattack! Its ability to produce is now severely limited.');
INSERT INTO events VALUES (6, 'Ransomware Attack!', 'One of your stores has been hit by a Ransomware attack! It will be unable to function until you pay to unlock it.');
INSERT INTO events VALUES (7, 'Sponsership Achieved!', 'A sponsorship deal has been brokered with a famous brand! Income will increase as a result of this partnership.');
INSERT INTO events VALUES (8, 'Strike!', 'There is an employee strike ongoing in one of your stores! Trade is halted until the strike is over.');
INSERT INTO events VALUES (9, 'Layoffs!', 'One of your stores has laid off a portion of its staff! Productivity has been reduced from this store.');
INSERT INTO events VALUES (10, 'Inflation!', 'Economic inflation has lessned the value of currencies. Wealth and income is negatively impacted.');
INSERT INTO events VALUES (11, 'Real Estate Crash!', 'The real estate market in a city has experienced a crash! Populations will shift more often as a result.');
INSERT INTO events VALUES (12, 'Stock Market Crash!', 'The Stock Market in a city has experienced a crash! Wealth and income to stores in this city are negatively impacted.');
INSERT INTO events VALUES (13, 'Economic Boom!', 'The global economy is in a booming period! Wealth and productivity are sure to rise as a result.');
INSERT INTO events VALUES (14, 'Surging Demand!', 'There is great demand for a product! Stores selling this product wills sell more as a result');
INSERT INTO events VALUES (15, 'Celebrity Promotion', 'One of your stores has been granted an endorsement from a famous figure! Income from this store will be boosted from this exposure.');
INSERT INTO events VALUES (16, 'Baby Boom!', 'Births have been increasing substantially around the globe! The population will increase globally.');
INSERT INTO events VALUES (17, 'Investment Deal!', 'A investor has decided to purchase stock in one of your stores! Productivity will be increased due to this contribution.');
INSERT INTO product VALUES ('Cell Phone', 650, 450);
INSERT INTO product VALUES ('Office PC', 750, 470);
INSERT INTO product VALUES ('Laptop', 1230, 800);
INSERT INTO product VALUES ('Gaming PC', 2150, 1130);
INSERT INTO product VALUES ('Workstation PC', 3180, 1550);
INSERT INTO product VALUES ('Sedan', 15330, 10240);
INSERT INTO product VALUES ('Truck', 25340, 18000);
INSERT INTO product VALUES ('SUV', 40320, 27300);
INSERT INTO product VALUES ('Electric Vehicle', 53230, 32330);
INSERT INTO product VALUES ('Luxury Vehicle', 123380, 85300);
INSERT INTO product VALUES ('Luxury Accessories', 540, 230);
INSERT INTO product VALUES ('Luxury Clothes', 1020, 550);
INSERT INTO product VALUES ('Luxury Handbag', 2580, 1330);
INSERT INTO product VALUES ('Luxury Watch', 13230, 8530);
INSERT INTO product VALUES ('Tricycle', 290, 130);
INSERT INTO product VALUES ('City Bike', 450, 250);
INSERT INTO product VALUES ('Mountain Bike', 880, 460);
INSERT INTO product VALUES ('Racing Bike', 1530, 780);
INSERT INTO product VALUES ('Basic Sneakers', 60, 35);
INSERT INTO product VALUES ('Shoes', 200, 110);
INSERT INTO product VALUES ('Boot', 320, 190);
INSERT INTO product VALUES ('Brand Shoes', 500, 300);
INSERT INTO product VALUES ('Music DVD', 40, 25);
INSERT INTO product VALUES ('Movie DVD', 60, 35);
INSERT INTO product VALUES ('Vinyl Album', 100, 60);
INSERT INTO product VALUES ('Video Game', 120, 60);
INSERT INTO product VALUES ('Basic Tools', 80, 45);
INSERT INTO product VALUES ('Quality Tools', 150, 85);
INSERT INTO product VALUES ('Power Tools', 320, 170);
INSERT INTO product VALUES ('Novel', 30, 20);
INSERT INTO product VALUES ('Cook Book', 40, 20);
INSERT INTO product VALUES ('Art Book', 80, 45);
INSERT INTO product VALUES ('Textbook', 250, 170);
INSERT INTO product VALUES ('Dinghy', 300, 190);
INSERT INTO product VALUES ('Kayak', 350, 200);
INSERT INTO product VALUES ('Jet Ski', 1130, 770);
INSERT INTO product VALUES ('Motorboat', 5670, 3200);
INSERT INTO product VALUES ('Jet Boat', 35320, 20350);
INSERT INTO product VALUES ('Yacht', 154560, 95480);
INSERT INTO city VALUES ('Mexico City', 'Mexico', 21505000, 19.4333, -99.1333, 'One of the oldest capital cities in the Americas, and the sixth largest metropolitian area in the world. The area is reknowned for high productivity and is a major tourist destination. It is home to a large retail market that ranges from basic items to luxury goods.', 60, 'Vehicle Store,Bicycle Store,Shoe Store,Hardware Store,Boat Store');
INSERT INTO city VALUES ('Johannesburg', 'South Africa', 4434000, -26.2044, 28.0416, 'The economic and finacial hub of South Africa, the city was formerly a foundation for mining but manufacturing and retail have become greater contributers to Johannesburg''s economy with time. The city has an abundance of heavy industries, retail, IT and transportation markets.', 50, 'Computer Store,Bicycle Store,Media Store,Boat Store');
INSERT INTO city VALUES ('Toronto', 'Canada', 6313000, 43.65107, -79.347015, 'Home to a population of 6.3 million people with 230 different nationalities, Toronto is one of if not the most diverse city in the world. It is a hub for the entire country''s financial, commercial, industrial, and tech industries.', 70, 'Vehicle Store,Computer Store,Media Store,Hardware Store,Book Store');
INSERT INTO city VALUES ('Buenos Aires', 'Argentina', 16216000, -34.5997, -58.3819, 'Ranked as being among the cities with the best quality of life in Latin America, Buenos Aires is a large eclectic city rich with culture. It has a large tourism scene, and a significant manufacturing sector where agriculture and and industry converge.', 60, 'Computer Store,Fashion Store,Shoe Store,Boat Store,Hardware Store');        
INSERT INTO city VALUES ('Sao Paulo', 'Brazil', 1060000, -23.5504, -46.6339, 'The fourth largest city by population, and the strongest international commercial, financial and entertainment hub in Latin America, Sao Paulo has rich diversity and a shifting focus from industry to service based economy. Sao Paulo is home to many international companies that call their city their HQ.', 55, 'Computer Store,Bicycle Store,Shoe Store,Boat Store');
INSERT INTO city VALUES ('New York City', 'United States of America', 18713000, 40.6943, -73.9249, 'Being one of the most densely populated cities in the US, New York is one of the largest metroplitan areas in the world, and is considered one of the pinnacles of culture, financial, and media centres in the world.', 100, 'Vehicle Store,Computer Store,Fashion Store,Book Store,Boat Store');
INSERT INTO city VALUES ('Los Angeles', 'United States of America', 12750000, 34.1139, -118.4068, 'Also known as simply ''LA'', Los Angeles is well known for it''s diversity and being situated in the most populous county in the US. It is the home of Hollywood and a cultural center in the southwest US.', 90, 'Vehicle Store,Shoe Store,Media Store,Book Store,Boat Store');
INSERT INTO city VALUES ('Dubai', 'United Arab Emirates', 2502715, 25.2697, 55.3094, 'For a long time serving as a hub for international trade, Dubai saw rapid growth and evelopment with its economy centered on tourism, aviation, and financial services. The city is well reknowned for tourism and luxury, as well as having the tallest building in the world, the Burj Khalifa.', 80, 'Vehicle Store,Computer Store,Book Store,Hardware Store,Boat Store');
INSERT INTO city VALUES ('Moscow', 'Russia', 17693000, 55.7558, 37.6178, 'The political and economic center of Eurasia, Moscow serves as the home to various artists, scientists, and athletes. Moscow is the site of many Russian companies with an emphasis on transportation.', 60, 'Vehicle Store,Computer Store,Book Store,Shoe Store,Hardware Store');
INSERT INTO city VALUES ('Rome', 'Italy', 2872000, 41.8931, 12.4828, 'Known as the ''Eternal City'', the ancient city of Rome is reknowned for its brands in fashion, design, and autombile industry. With a provenance of cultural and artistic merit, it is an important city for tourism and fashion.', 80, 'Fashion Store,Shoe Store,Media Store,Book Store,Boat Store');
INSERT INTO city VALUES ('Paris', 'France', 11027000, 48.8566, 2.3522, 'The historical city of Paris has been a leading centre for finance, fashion, gastronomy, and science since the 17th century. A trend that continues to the modern day.', 75, 'Fashion Store,Shoe Store,Media Store,Book Store');
INSERT INTO city VALUES ('Berlin', 'Germany', 3664088, 52.5167, 13.3833, 'Home to a massive enetrepeneurial scene, Berlin is a thriving centre of creative industries, science, and media. The German capital is a popular tourist location and particularly important with the automobile market', 65, 'Vehicle Store,Computer Store,Bicycle Store,Media Store,Book Store');
INSERT INTO city VALUES ('Bangkok', 'Thailand', 17573000, 13.75, 100.5167, 'An emerging centre for arts, fashion, and street culture. Bangkok is a significant tourist destination that has seen rapid urban growth. There is a massive car market as a result of its growth.', 60, 'Shoe Store,Media Store,Book Store,Boat Store');
INSERT INTO city VALUES ('Melbourne', 'Australia', 17573000, -37.8136, 144.9631, 'The largest city of Australia, Melbourne is home to many Australian landmarks, and is a site of sports, art and entertainment.', 60, 'Vehicle Store,Computer Store,Bicycle Store,Media Store,Boat Store');
INSERT INTO city VALUES ('Beijing', 'People''s Republic of China', 19437000, 39.904, 116.4075, 'One of the most populous capital city in the world. It is a leading centre for culture, politics, finance, and business in Asia and one of the largest industrial centres in the world.', 80, 'Vehicle Store,Computer Store,Bicycle Store,Shoe Store,Hardware Store');
INSERT INTO city VALUES ('Tokyo', 'Japan', 39105000, 35.6839, 139.7744, 'The capital city of Japan, and the most populous city in the world. Tokyo is the seat of government in Japan and serves as the country''s economic center.', 90, 'Vehicle Store,Fashion Store,Shoe Store,Media Store,Book Store');